# Generated by Django 3.2.8 on 2021-11-01 14:43

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=shop.models.price_default, max_digits=11)),
                ('available', models.BooleanField(default=shop.models.available_default)),
                ('description', models.TextField(default='')),
                ('specifications', models.JSONField(default=shop.models.json_default)),
                ('type_of_filament', models.CharField(max_length=20)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=shop.models.price_default, max_digits=11)),
                ('available', models.BooleanField(default=shop.models.available_default)),
                ('description', models.TextField(default='')),
                ('specifications', models.JSONField(default=shop.models.json_default)),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=shop.models.price_default, max_digits=11)),
                ('available', models.BooleanField(default=shop.models.available_default)),
                ('description', models.TextField(default='')),
                ('specifications', models.JSONField(default=shop.models.json_default)),
                ('manufacturer', models.CharField(max_length=30)),
                ('kinematics_type', models.CharField(max_length=20)),
            ],
        ),
    ]
